# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from whats_app_business_python_sdk import WhatsAppBusiness

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        whatsappbusiness = WhatsAppBusiness(
        
            access_token = 'YOUR_BEARER_TOKEN',
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD'
        )
        self.assertIsNotNone(whatsappbusiness)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
