# coding: utf-8
"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from whats_app_business_python_sdk.client_custom import ClientCustom
from whats_app_business_python_sdk.configuration import Configuration
from whats_app_business_python_sdk.api_client import ApiClient
from whats_app_business_python_sdk.type_util import copy_signature
from whats_app_business_python_sdk.apis.tags.application_api import ApplicationApi
from whats_app_business_python_sdk.apis.tags.backup_restore_api import BackupRestoreApi
from whats_app_business_python_sdk.apis.tags.business_profile_api import BusinessProfileApi
from whats_app_business_python_sdk.apis.tags.certificates_api import CertificatesApi
from whats_app_business_python_sdk.apis.tags.contacts_api import ContactsApi
from whats_app_business_python_sdk.apis.tags.groups_api import GroupsApi
from whats_app_business_python_sdk.apis.tags.health_api import HealthApi
from whats_app_business_python_sdk.apis.tags.media_api import MediaApi
from whats_app_business_python_sdk.apis.tags.messages_api import MessagesApi
from whats_app_business_python_sdk.apis.tags.profile_api import ProfileApi
from whats_app_business_python_sdk.apis.tags.registration_api import RegistrationApi
from whats_app_business_python_sdk.apis.tags.two_step_verification_api import TwoStepVerificationApi
from whats_app_business_python_sdk.apis.tags.users_api import UsersApi



class WhatsAppBusiness(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.application: ApplicationApi = ApplicationApi(api_client)
        self.backup/restore: BackupRestoreApi = BackupRestoreApi(api_client)
        self.business_profile: BusinessProfileApi = BusinessProfileApi(api_client)
        self.certificates: CertificatesApi = CertificatesApi(api_client)
        self.contacts: ContactsApi = ContactsApi(api_client)
        self.groups: GroupsApi = GroupsApi(api_client)
        self.health: HealthApi = HealthApi(api_client)
        self.media: MediaApi = MediaApi(api_client)
        self.messages: MessagesApi = MessagesApi(api_client)
        self.profile: ProfileApi = ProfileApi(api_client)
        self.registration: RegistrationApi = RegistrationApi(api_client)
        self.two_step_verification: TwoStepVerificationApi = TwoStepVerificationApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
