# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from whats_app_business_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from whats_app_business_python_sdk.api_response import AsyncGeneratorResponse
from whats_app_business_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from whats_app_business_python_sdk import schemas  # noqa: F401

from whats_app_business_python_sdk.model.application_settings import ApplicationSettings as ApplicationSettingsSchema
from whats_app_business_python_sdk.model.media import Media as MediaSchema
from whats_app_business_python_sdk.model.webhooks import Webhooks as WebhooksSchema
from whats_app_business_python_sdk.model.response import Response as ResponseSchema

from whats_app_business_python_sdk.type.webhooks import Webhooks
from whats_app_business_python_sdk.type.media import Media
from whats_app_business_python_sdk.type.response import Response
from whats_app_business_python_sdk.type.application_settings import ApplicationSettings

from ...api_client import Dictionary
from whats_app_business_python_sdk.pydantic.application_settings import ApplicationSettings as ApplicationSettingsPydantic
from whats_app_business_python_sdk.pydantic.media import Media as MediaPydantic
from whats_app_business_python_sdk.pydantic.response import Response as ResponsePydantic
from whats_app_business_python_sdk.pydantic.webhooks import Webhooks as WebhooksPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = ApplicationSettingsSchema


request_body_application_settings = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'bearerAuth',
]
SchemaFor200ResponseBodyApplicationJson = ResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: Response


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: Response


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_settings_mapped_args(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if callback_backoff_delay_ms is not None:
            _body["callback_backoff_delay_ms"] = callback_backoff_delay_ms
        if callback_persist is not None:
            _body["callback_persist"] = callback_persist
        if heartbeat_interval is not None:
            _body["heartbeat_interval"] = heartbeat_interval
        if max_callback_backoff_delay_ms is not None:
            _body["max_callback_backoff_delay_ms"] = max_callback_backoff_delay_ms
        if media is not None:
            _body["media"] = media
        if on_call_pager is not None:
            _body["on_call_pager"] = on_call_pager
        if pass_through is not None:
            _body["pass_through"] = pass_through
        if sent_status is not None:
            _body["sent_status"] = sent_status
        if unhealthy_interval is not None:
            _body["unhealthy_interval"] = unhealthy_interval
        if webhooks is not None:
            _body["webhooks"] = webhooks
        args.body = _body
        return args

    async def _aupdate_settings_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Update-Application-Settings
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/settings/application',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_application_settings.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_settings_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Update-Application-Settings
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/settings/application',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_application_settings.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdateSettingsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_settings(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_settings_mapped_args(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
        )
        return await self._aupdate_settings_oapg(
            body=args.body,
            **kwargs,
        )
    
    def update_settings(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_settings_mapped_args(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
        )
        return self._update_settings_oapg(
            body=args.body,
        )

class UpdateSettings(BaseApi):

    async def aupdate_settings(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
        validate: bool = False,
        **kwargs,
    ) -> ResponsePydantic:
        raw_response = await self.raw.aupdate_settings(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
            **kwargs,
        )
        if validate:
            return ResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ResponsePydantic, raw_response.body)
    
    
    def update_settings(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
        validate: bool = False,
    ) -> ResponsePydantic:
        raw_response = self.raw.update_settings(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
        )
        if validate:
            return ResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ResponsePydantic, raw_response.body)


class ApiForpatch(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apatch(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_settings_mapped_args(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
        )
        return await self._aupdate_settings_oapg(
            body=args.body,
            **kwargs,
        )
    
    def patch(
        self,
        callback_backoff_delay_ms: typing.Optional[str] = None,
        callback_persist: typing.Optional[bool] = None,
        heartbeat_interval: typing.Optional[int] = None,
        max_callback_backoff_delay_ms: typing.Optional[str] = None,
        media: typing.Optional[Media] = None,
        on_call_pager: typing.Optional[str] = None,
        pass_through: typing.Optional[bool] = None,
        sent_status: typing.Optional[bool] = None,
        unhealthy_interval: typing.Optional[int] = None,
        webhooks: typing.Optional[Webhooks] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_settings_mapped_args(
            callback_backoff_delay_ms=callback_backoff_delay_ms,
            callback_persist=callback_persist,
            heartbeat_interval=heartbeat_interval,
            max_callback_backoff_delay_ms=max_callback_backoff_delay_ms,
            media=media,
            on_call_pager=on_call_pager,
            pass_through=pass_through,
            sent_status=sent_status,
            unhealthy_interval=unhealthy_interval,
            webhooks=webhooks,
        )
        return self._update_settings_oapg(
            body=args.body,
        )

