# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from whats_app_business_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from whats_app_business_python_sdk.api_response import AsyncGeneratorResponse
from whats_app_business_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from whats_app_business_python_sdk import schemas  # noqa: F401

from whats_app_business_python_sdk.model.text import Text as TextSchema
from whats_app_business_python_sdk.model.hsm import Hsm as HsmSchema
from whats_app_business_python_sdk.model.message_type import MessageType as MessageTypeSchema
from whats_app_business_python_sdk.model.location import Location as LocationSchema
from whats_app_business_python_sdk.model.document import Document as DocumentSchema
from whats_app_business_python_sdk.model.image import Image as ImageSchema
from whats_app_business_python_sdk.model.message_response import MessageResponse as MessageResponseSchema
from whats_app_business_python_sdk.model.audio import Audio as AudioSchema
from whats_app_business_python_sdk.model.send_message_request_body import SendMessageRequestBody as SendMessageRequestBodySchema
from whats_app_business_python_sdk.model.video import Video as VideoSchema
from whats_app_business_python_sdk.model.contact import Contact as ContactSchema

from whats_app_business_python_sdk.type.hsm import Hsm
from whats_app_business_python_sdk.type.document import Document
from whats_app_business_python_sdk.type.image import Image
from whats_app_business_python_sdk.type.contact import Contact
from whats_app_business_python_sdk.type.video import Video
from whats_app_business_python_sdk.type.text import Text
from whats_app_business_python_sdk.type.send_message_request_body import SendMessageRequestBody
from whats_app_business_python_sdk.type.message_type import MessageType
from whats_app_business_python_sdk.type.location import Location
from whats_app_business_python_sdk.type.message_response import MessageResponse
from whats_app_business_python_sdk.type.audio import Audio

from ...api_client import Dictionary
from whats_app_business_python_sdk.pydantic.hsm import Hsm as HsmPydantic
from whats_app_business_python_sdk.pydantic.message_response import MessageResponse as MessageResponsePydantic
from whats_app_business_python_sdk.pydantic.contact import Contact as ContactPydantic
from whats_app_business_python_sdk.pydantic.video import Video as VideoPydantic
from whats_app_business_python_sdk.pydantic.audio import Audio as AudioPydantic
from whats_app_business_python_sdk.pydantic.location import Location as LocationPydantic
from whats_app_business_python_sdk.pydantic.text import Text as TextPydantic
from whats_app_business_python_sdk.pydantic.send_message_request_body import SendMessageRequestBody as SendMessageRequestBodyPydantic
from whats_app_business_python_sdk.pydantic.message_type import MessageType as MessageTypePydantic
from whats_app_business_python_sdk.pydantic.document import Document as DocumentPydantic
from whats_app_business_python_sdk.pydantic.image import Image as ImagePydantic

# body param
SchemaForRequestBodyApplicationJson = SendMessageRequestBodySchema


request_body_send_message_request_body = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = MessageResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: MessageResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: MessageResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _send_message_mapped_args(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if audio is not None:
            _body["audio"] = audio
        if contacts is not None:
            _body["contacts"] = contacts
        if document is not None:
            _body["document"] = document
        if hsm is not None:
            _body["hsm"] = hsm
        if image is not None:
            _body["image"] = image
        if location is not None:
            _body["location"] = location
        if preview_url is not None:
            _body["preview_url"] = preview_url
        if recipient_type is not None:
            _body["recipient_type"] = recipient_type
        if text is not None:
            _body["text"] = text
        if to is not None:
            _body["to"] = to
        if ttl is not None:
            _body["ttl"] = ttl
        if type is not None:
            _body["type"] = type
        if video is not None:
            _body["video"] = video
        args.body = _body
        return args

    async def _asend_message_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Send-Message
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/messages',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_send_message_request_body.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _send_message_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Send-Message
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/messages',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_send_message_request_body.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class SendMessageRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def asend_message(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._send_message_mapped_args(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
        )
        return await self._asend_message_oapg(
            body=args.body,
            **kwargs,
        )
    
    def send_message(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._send_message_mapped_args(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
        )
        return self._send_message_oapg(
            body=args.body,
        )

class SendMessage(BaseApi):

    async def asend_message(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
        validate: bool = False,
        **kwargs,
    ) -> MessageResponsePydantic:
        raw_response = await self.raw.asend_message(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
            **kwargs,
        )
        if validate:
            return RootModel[MessageResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(MessageResponsePydantic, raw_response.body)
    
    
    def send_message(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
        validate: bool = False,
    ) -> MessageResponsePydantic:
        raw_response = self.raw.send_message(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
        )
        if validate:
            return RootModel[MessageResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(MessageResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._send_message_mapped_args(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
        )
        return await self._asend_message_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        to: str,
        audio: typing.Optional[Audio] = None,
        contacts: typing.Optional[typing.List[Contact]] = None,
        document: typing.Optional[Document] = None,
        hsm: typing.Optional[Hsm] = None,
        image: typing.Optional[Image] = None,
        location: typing.Optional[Location] = None,
        preview_url: typing.Optional[bool] = None,
        recipient_type: typing.Optional[str] = None,
        text: typing.Optional[Text] = None,
        ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        type: typing.Optional[MessageType] = None,
        video: typing.Optional[Video] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._send_message_mapped_args(
            to=to,
            audio=audio,
            contacts=contacts,
            document=document,
            hsm=hsm,
            image=image,
            location=location,
            preview_url=preview_url,
            recipient_type=recipient_type,
            text=text,
            ttl=ttl,
            type=type,
            video=video,
        )
        return self._send_message_oapg(
            body=args.body,
        )

