# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import whats_app_business_python_sdk
from whats_app_business_python_sdk.model.certificates_download_webhook_ca_certificate_response import CertificatesDownloadWebhookCaCertificateResponse
from whats_app_business_python_sdk import configuration


class TestCertificatesDownloadWebhookCaCertificateResponse(unittest.TestCase):
    """CertificatesDownloadWebhookCaCertificateResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
