# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import whats_app_business_python_sdk
from whats_app_business_python_sdk.model.update_group_info_request_body import UpdateGroupInfoRequestBody
from whats_app_business_python_sdk import configuration


class TestUpdateGroupInfoRequestBody(unittest.TestCase):
    """UpdateGroupInfoRequestBody unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
