# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import whats_app_business_python_sdk
from whats_app_business_python_sdk.model.group_info_participants import GroupInfoParticipants
from whats_app_business_python_sdk import configuration


class TestGroupInfoParticipants(unittest.TestCase):
    """GroupInfoParticipants unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
