# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.settings_application.get import GetSettings
from whats_app_business_python_sdk.paths.settings_application_media_providers.get import ListMediaProviders
from whats_app_business_python_sdk.paths.settings_application_media_providers_provider_name.delete import RemoveProvider
from whats_app_business_python_sdk.paths.settings_application.delete import ResetSettings
from whats_app_business_python_sdk.paths.account_shards.post import SetShards
from whats_app_business_python_sdk.paths.settings_application_media_providers.post import UpdateMediaProviders
from whats_app_business_python_sdk.paths.settings_application.patch import UpdateSettings
from whats_app_business_python_sdk.apis.tags.application_api_raw import ApplicationApiRaw


class ApplicationApi(
    GetSettings,
    ListMediaProviders,
    RemoveProvider,
    ResetSettings,
    SetShards,
    UpdateMediaProviders,
    UpdateSettings,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApplicationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApplicationApiRaw(api_client)
