# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.settings_application.get import GetSettingsRaw
from whats_app_business_python_sdk.paths.settings_application_media_providers.get import ListMediaProvidersRaw
from whats_app_business_python_sdk.paths.settings_application_media_providers_provider_name.delete import RemoveProviderRaw
from whats_app_business_python_sdk.paths.settings_application.delete import ResetSettingsRaw
from whats_app_business_python_sdk.paths.account_shards.post import SetShardsRaw
from whats_app_business_python_sdk.paths.settings_application_media_providers.post import UpdateMediaProvidersRaw
from whats_app_business_python_sdk.paths.settings_application.patch import UpdateSettingsRaw


class ApplicationApiRaw(
    GetSettingsRaw,
    ListMediaProvidersRaw,
    RemoveProviderRaw,
    ResetSettingsRaw,
    SetShardsRaw,
    UpdateMediaProvidersRaw,
    UpdateSettingsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
