# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.settings_backup.post import SettingsPost
from whats_app_business_python_sdk.paths.settings_restore.post import SettingsPost0
from whats_app_business_python_sdk.apis.tags.backup_restore_api_raw import BackupRestoreApiRaw


class BackupRestoreApi(
    SettingsPost,
    SettingsPost0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BackupRestoreApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BackupRestoreApiRaw(api_client)
