# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.settings_business_profile.get import GetRaw
from whats_app_business_python_sdk.paths.settings_business_profile.post import UpdateRaw


class BusinessProfileApiRaw(
    GetRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
