# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.settings_business_profile.get import Get
from whats_app_business_python_sdk.paths.settings_business_profile.post import Update
from whats_app_business_python_sdk.apis.tags.business_profile_api_raw import BusinessProfileApiRaw


class BusinessProfileApi(
    Get,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BusinessProfileApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BusinessProfileApiRaw(api_client)
