# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.certificates_webhooks_ca.delete import DeleteWebhookCaRaw
from whats_app_business_python_sdk.paths.certificates_external_ca.get import DownloadCaCertificateRaw
from whats_app_business_python_sdk.paths.certificates_webhooks_ca.get import DownloadWebhookCaCertificateRaw
from whats_app_business_python_sdk.paths.certificates_external.post import UploadExternalCertificateRaw
from whats_app_business_python_sdk.paths.certificates_webhooks_ca.post import UploadWebhookCaCertificateRaw


class CertificatesApiRaw(
    DeleteWebhookCaRaw,
    DownloadCaCertificateRaw,
    DownloadWebhookCaCertificateRaw,
    UploadExternalCertificateRaw,
    UploadWebhookCaCertificateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
