# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.groups.post import CreateGroup
from whats_app_business_python_sdk.paths.groups_group_id_icon.delete import DeleteGroupIcon
from whats_app_business_python_sdk.paths.groups_group_id_invite.delete import DeleteInvite
from whats_app_business_python_sdk.paths.groups_group_id_admins.delete import DemoteAdmin
from whats_app_business_python_sdk.paths.groups.get import GetAll
from whats_app_business_python_sdk.paths.groups_group_id_icon.get import GetIconBinary
from whats_app_business_python_sdk.paths.groups_group_id.get import GetInfo
from whats_app_business_python_sdk.paths.groups_group_id_invite.get import GetInviteDetails
from whats_app_business_python_sdk.paths.groups_group_id_leave.post import LeaveGroup
from whats_app_business_python_sdk.paths.groups_group_id_admins.patch import PromoteToAdmin
from whats_app_business_python_sdk.paths.groups_group_id_participants.delete import RemoveParticipant
from whats_app_business_python_sdk.paths.groups_group_id_icon.post import SetGroupIcon
from whats_app_business_python_sdk.paths.groups_group_id.put import UpdateInfo
from whats_app_business_python_sdk.apis.tags.groups_api_raw import GroupsApiRaw


class GroupsApi(
    CreateGroup,
    DeleteGroupIcon,
    DeleteInvite,
    DemoteAdmin,
    GetAll,
    GetIconBinary,
    GetInfo,
    GetInviteDetails,
    LeaveGroup,
    PromoteToAdmin,
    RemoveParticipant,
    SetGroupIcon,
    UpdateInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GroupsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GroupsApiRaw(api_client)
