# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.media_media_id.get import Download
from whats_app_business_python_sdk.paths.media_media_id.delete import RemoveMedia
from whats_app_business_python_sdk.paths.media.post import UploadMedia
from whats_app_business_python_sdk.apis.tags.media_api_raw import MediaApiRaw


class MediaApi(
    Download,
    RemoveMedia,
    UploadMedia,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MediaApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MediaApiRaw(api_client)
