# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.media_media_id.get import DownloadRaw
from whats_app_business_python_sdk.paths.media_media_id.delete import RemoveMediaRaw
from whats_app_business_python_sdk.paths.media.post import UploadMediaRaw


class MediaApiRaw(
    DownloadRaw,
    RemoveMediaRaw,
    UploadMediaRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
