# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.messages_message_id.put import MarkAsReadRaw
from whats_app_business_python_sdk.paths.messages.post import SendMessageRaw


class MessagesApiRaw(
    MarkAsReadRaw,
    SendMessageRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
