# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.messages_message_id.put import MarkAsRead
from whats_app_business_python_sdk.paths.messages.post import SendMessage
from whats_app_business_python_sdk.apis.tags.messages_api_raw import MessagesApiRaw


class MessagesApi(
    MarkAsRead,
    SendMessage,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MessagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MessagesApiRaw(api_client)
