# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.account.post import RequestCodeRaw
from whats_app_business_python_sdk.paths.account_verify.post import VerifyAccountRaw


class RegistrationApiRaw(
    RequestCodeRaw,
    VerifyAccountRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
