# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from whats_app_business_python_sdk.paths.users.post import CreateUser
from whats_app_business_python_sdk.paths.users_user_username.get import GetByUsername
from whats_app_business_python_sdk.paths.users_login.post import PerformLogin
from whats_app_business_python_sdk.paths.users_logout.post import PerformLogout
from whats_app_business_python_sdk.paths.users_user_username.delete import RemoveUser
from whats_app_business_python_sdk.paths.users_user_username.put import UpdateUser
from whats_app_business_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    CreateUser,
    GetByUsername,
    PerformLogin,
    PerformLogout,
    RemoveUser,
    UpdateUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
