# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAddress(TypedDict):
    # City name
    city: str

    # Full country name
    country: str

    # Two-letter country abbreviation
    country_code: str

    # State abbreviation
    state: str

    # Street number and name
    street: str

    # Standard Values: HOME, WORK
    type: str

    # ZIP code
    zip: str

class OptionalAddress(TypedDict, total=False):
    pass

class Address(RequiredAddress, OptionalAddress):
    pass
