# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBackupSettingsRequestBody(TypedDict):
    # Used to encrypt backup data for security
    password: str

class OptionalBackupSettingsRequestBody(TypedDict, total=False):
    pass

class BackupSettingsRequestBody(RequiredBackupSettingsRequestBody, OptionalBackupSettingsRequestBody):
    pass
