# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBackupSettings(TypedDict):
    pass

class OptionalBackupSettings(TypedDict, total=False):
    # The data that has been backed up, encrypted for security.
    data: str

class BackupSettings(RequiredBackupSettings, OptionalBackupSettings):
    pass
