# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.business_settings_business import BusinessSettingsBusiness

class RequiredBusinessSettings(TypedDict):
    pass

class OptionalBusinessSettings(TypedDict, total=False):
    business: BusinessSettingsBusiness

class BusinessSettings(RequiredBusinessSettings, OptionalBusinessSettings):
    pass
