# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.check_contact_request_body_contacts import CheckContactRequestBodyContacts

class RequiredCheckContactRequestBody(TypedDict):
    contacts: CheckContactRequestBodyContacts

class OptionalCheckContactRequestBody(TypedDict, total=False):
    # Blocking determines whether the request should wait for the processing to complete (synchronous) or not (asynchronous).
    blocking: str

class CheckContactRequestBody(RequiredCheckContactRequestBody, OptionalCheckContactRequestBody):
    pass
