# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGroupsSetGroupIconRequest(TypedDict):
    File: typing.IO

class OptionalGroupsSetGroupIconRequest(TypedDict, total=False):
    pass

class GroupsSetGroupIconRequest(RequiredGroupsSetGroupIconRequest, OptionalGroupsSetGroupIconRequest):
    pass
