# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.group_info_admins import GroupInfoAdmins
from whats_app_business_python_sdk.type.group_info_participants import GroupInfoParticipants

class RequiredGroupInfo(TypedDict):
    pass

class OptionalGroupInfo(TypedDict, total=False):
    admins: GroupInfoAdmins

    # Group creation time
    creation_time: int

    # ID of the creator of this group
    creator: str

    participants: GroupInfoParticipants

    # Subject of the group
    subject: str

class GroupInfo(RequiredGroupInfo, OptionalGroupInfo):
    pass
