# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.language import Language
from whats_app_business_python_sdk.type.localizable_param import LocalizableParam

class RequiredHsm(TypedDict):
    # The element name that indicates which template to use within the namespace
    element_name: str

    language: Language

    # This field is an array of values to apply to variables in the template
    localizable_params: typing.List[LocalizableParam]

    # The namespace that will be used
    namespace: str

class OptionalHsm(TypedDict, total=False):
    pass

class Hsm(RequiredHsm, OptionalHsm):
    pass
