# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLanguage(TypedDict):
    # The code of the language or locale to use — Accepts both language and language_locale formats (e.g., en and en_US).
    code: str

    # The language policy the message should follow
    policy: str

class OptionalLanguage(TypedDict, total=False):
    pass

class Language(RequiredLanguage, OptionalLanguage):
    pass
