# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLocation(TypedDict):
    # Address of the location. Only displayed if name is present.
    address: str

    # Latitude of the location
    latitude: str

    # Longitude of the location
    longitude: str

    # Name of the location
    name: str

class OptionalLocation(TypedDict, total=False):
    pass

class Location(RequiredLocation, OptionalLocation):
    pass
