# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.config import Config

class RequiredMediaProvider(TypedDict):
    pass

class OptionalMediaProvider(TypedDict, total=False):
    config: Config

    # The name for the provider
    name: str

    # The type of provider
    type: str

class MediaProvider(RequiredMediaProvider, OptionalMediaProvider):
    pass
