# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.message_context_mentions import MessageContextMentions

RequiredMessageContext = TypedDict("RequiredMessageContext", {
    })

OptionalMessageContext = TypedDict("OptionalMessageContext", {
    # Sender Whatsapp id of context-message
    "from": str,

    # GroupId of context message
    "group_id": str,

    # message id
    "id": str,

    "mentions": MessageContextMentions,
    }, total=False)

class MessageContext(RequiredMessageContext, OptionalMessageContext):
    pass
