# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredName(TypedDict):
    # Full name as it normally appears
    formatted_name: str

class OptionalName(TypedDict, total=False):
    # First name
    first_name: str

    # Last name
    last_name: str

    # Name preffix
    prefix: str

    # Name suffix
    suffix: str

class Name(RequiredName, OptionalName):
    pass
