# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPhone(TypedDict):
    pass

class OptionalPhone(TypedDict, total=False):
    phone: str

    # Standard Values: CELL, MAIN, IPHONE, HOME, WORK
    type: str

    # WhatsApp ID
    wa_id: str

class Phone(RequiredPhone, OptionalPhone):
    pass
