# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProfileAbout(TypedDict):
    # Text to display in your profile's About section The max length for the string is 139 characters.
    text: str

class OptionalProfileAbout(TypedDict, total=False):
    pass

class ProfileAbout(RequiredProfileAbout, OptionalProfileAbout):
    pass
