# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProfilePhotoSettingsProfilePhoto(TypedDict):
    pass

class OptionalProfilePhotoSettingsProfilePhoto(TypedDict, total=False):
    link: str

class ProfilePhotoSettingsProfilePhoto(RequiredProfilePhotoSettingsProfilePhoto, OptionalProfilePhotoSettingsProfilePhoto):
    pass
