# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRequestCodeRequestBody(TypedDict):
    # Numerical country code for the phone number you are registering
    cc: str

    # Base64-encoded Verified Name certificate
    cert: str

    # Method of receiving your registration code
    method: str

    # Phone number you are registering, without the country code or plus symbol (+)
    phone_number: str

class OptionalRequestCodeRequestBody(TypedDict, total=False):
    # Existing 6-digit PIN — This is only required when two-factor verification is enabled on this account.
    pin: str

class RequestCodeRequestBody(RequiredRequestCodeRequestBody, OptionalRequestCodeRequestBody):
    pass
