# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.error import Error
from whats_app_business_python_sdk.type.meta import Meta

class RequiredResponse(TypedDict):
    pass

class OptionalResponse(TypedDict, total=False):
    # Only returned with a failed request. Contains an array of error objects that are present when there is an error. 
    errors: typing.List[Error]

    meta: Meta

class Response(RequiredResponse, OptionalResponse):
    pass
