# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRestoreSettingsRequestBody(TypedDict):
    # The data that was returned by the /v1/settings/backup API call
    data: str

    # The password you used in the /v1/settings/backup API call to encrypt the backup data
    password: str

class OptionalRestoreSettingsRequestBody(TypedDict, total=False):
    pass

class RestoreSettingsRequestBody(RequiredRestoreSettingsRequestBody, OptionalRestoreSettingsRequestBody):
    pass
