# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.error import Error

class RequiredWebhookStatus(TypedDict):
    pass

class OptionalWebhookStatus(TypedDict, total=False):
    errors: typing.List[Error]

    # Message ID
    id: str

    # WhatsApp ID of recipient
    recipient_id: str

    # Status of message
    status: str

    # Timestamp of the status message
    timestamp: str

class WebhookStatus(RequiredWebhookStatus, OptionalWebhookStatus):
    pass
