# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.error import Error
from whats_app_business_python_sdk.type.webhook_contact import WebhookContact
from whats_app_business_python_sdk.type.webhook_message import WebhookMessage
from whats_app_business_python_sdk.type.webhook_status import WebhookStatus

class RequiredWebhookEvent(TypedDict):
    pass

class OptionalWebhookEvent(TypedDict, total=False):
    contacts: typing.List[WebhookContact]

    errors: typing.List[Error]

    messages: typing.List[WebhookMessage]

    statuses: typing.List[WebhookStatus]

class WebhookEvent(RequiredWebhookEvent, OptionalWebhookEvent):
    pass
