# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebhooks(TypedDict):
    pass

class OptionalWebhooks(TypedDict, total=False):
    # Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.
    max_concurrent_requests: int

    # Inbound and outbound notifications are routed to this URL. A HTTPS-based endpoint is required; HTTP will not work.
    url: str

class Webhooks(RequiredWebhooks, OptionalWebhooks):
    pass
