# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.contact import Contact
from whats_app_business_python_sdk.type.error import Error
from whats_app_business_python_sdk.type.message_context import MessageContext
from whats_app_business_python_sdk.type.message_type import MessageType
from whats_app_business_python_sdk.type.webhook_audio import WebhookAudio
from whats_app_business_python_sdk.type.webhook_document import WebhookDocument
from whats_app_business_python_sdk.type.webhook_image import WebhookImage
from whats_app_business_python_sdk.type.webhook_location import WebhookLocation
from whats_app_business_python_sdk.type.webhook_system import WebhookSystem
from whats_app_business_python_sdk.type.webhook_text import WebhookText
from whats_app_business_python_sdk.type.webhook_video import WebhookVideo
from whats_app_business_python_sdk.type.webhook_voice import WebhookVoice

RequiredWebhookMessage = TypedDict("RequiredWebhookMessage", {
    })

OptionalWebhookMessage = TypedDict("OptionalWebhookMessage", {
    "audio": WebhookAudio,

    "contacts": typing.List[Contact],

    "context": MessageContext,

    "document": WebhookDocument,

    "errors": typing.List[Error],

    # WhatsApp ID of the sender
    "from": str,

    # Optional. WhatsApp group ID
    "group_id": str,

    # Message ID
    "id": str,

    "image": WebhookImage,

    "location": WebhookLocation,

    "system": WebhookSystem,

    "text": WebhookText,

    # Message received timestamp
    "timestamp": str,

    "type": MessageType,

    "video": WebhookVideo,

    "voice": WebhookVoice,
    }, total=False)

class WebhookMessage(RequiredWebhookMessage, OptionalWebhookMessage):
    pass
