# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from whats_app_business_python_sdk.type.webhook_contact_profile import WebhookContactProfile

class RequiredWebhookContact(TypedDict):
    pass

class OptionalWebhookContact(TypedDict, total=False):
    profile: WebhookContactProfile

    # The WhatsApp ID of the contact
    wa_id: str

class WebhookContact(RequiredWebhookContact, OptionalWebhookContact):
    pass
