# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebhookLocation(TypedDict):
    pass

class OptionalWebhookLocation(TypedDict, total=False):
    # Address of the location
    address: str

    # Latitude of location being sent
    latitude: typing.Union[int, float]

    # Longitude of location being sent
    longitude: typing.Union[int, float]

    # Name of the location
    name: str

    # URL for the website where the user downloaded the location information
    url: str

class WebhookLocation(RequiredWebhookLocation, OptionalWebhookLocation):
    pass
