# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebhookAudio(TypedDict):
    pass

class OptionalWebhookAudio(TypedDict, total=False):
    # Optional. Only present if specified.
    caption: str

    # Absolute filename and location on media volume. This parameter is deprecated.
    file: str

    # Filename on the sender's device. This will only be present in audio and document media messages.
    filename: str

    # ID of the media. Can be used to delete the media if stored locally on the client.
    id: str

    link: str

    # Mime type of media
    mime_type: str

    # Checksum
    sha256: str

class WebhookAudio(RequiredWebhookAudio, OptionalWebhookAudio):
    pass
