# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from whats_app_business_python_sdk import schemas  # noqa: F401


class ApplicationUpdateMediaProvidersRequest(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['MediaProvider']:
            return MediaProvider

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['MediaProvider'], typing.List['MediaProvider']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ApplicationUpdateMediaProvidersRequest':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'MediaProvider':
        return super().__getitem__(i)

from whats_app_business_python_sdk.model.media_provider import MediaProvider
