# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from whats_app_business_python_sdk import schemas  # noqa: F401


class RemoveGroupParticipantRequestBody(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "wa_ids",
        }
        
        class properties:
        
            @staticmethod
            def wa_ids() -> typing.Type['RemoveGroupParticipantRequestBodyWaIds']:
                return RemoveGroupParticipantRequestBodyWaIds
            __annotations__ = {
                "wa_ids": wa_ids,
            }
    
    wa_ids: 'RemoveGroupParticipantRequestBodyWaIds'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wa_ids"]) -> 'RemoveGroupParticipantRequestBodyWaIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["wa_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wa_ids"]) -> 'RemoveGroupParticipantRequestBodyWaIds': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["wa_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        wa_ids: 'RemoveGroupParticipantRequestBodyWaIds',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RemoveGroupParticipantRequestBody':
        return super().__new__(
            cls,
            *args,
            wa_ids=wa_ids,
            _configuration=_configuration,
            **kwargs,
        )

from whats_app_business_python_sdk.model.remove_group_participant_request_body_wa_ids import RemoveGroupParticipantRequestBodyWaIds
