# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.media import Media
from whats_app_business_python_sdk.pydantic.webhooks import Webhooks

class ApplicationSettings(BaseModel):
    # Backoff delay for a failed callback in milliseconds This setting is used to configure the amount of time the backoff delays before retrying a failed callback. The backoff delay increases linearly by this value each time a callback fails to get a HTTPS 200 OK response. The backoff delay is capped by the max_callback_backoff_delay_ms setting.
    callback_backoff_delay_ms: typing.Optional[str] = Field(None, alias='callback_backoff_delay_ms')

    # Stores callbacks on disk until they are successfully acknowledged by the Webhook or not. Restart required.
    callback_persist: typing.Optional[bool] = Field(None, alias='callback_persist')

    # Multiconnect: Interval of the Master node monitoring of Coreapp nodes in seconds
    heartbeat_interval: typing.Optional[int] = Field(None, alias='heartbeat_interval')

    # Maximum delay for a failed callback in milliseconds
    max_callback_backoff_delay_ms: typing.Optional[str] = Field(None, alias='max_callback_backoff_delay_ms')

    media: typing.Optional[Media] = Field(None, alias='media')

    # Set to valid WhatsApp Group with users who wish to see alerts for critical errors and messages.
    on_call_pager: typing.Optional[str] = Field(None, alias='on_call_pager')

    # When true, removes messages from the local database after they are delivered to or read by the recipient. When false, saves all messages on local storage until they are explicitly deleted. When messages are sent, they are stored in a local database. This database is used as the application's history. Since the business keeps its own history, you can specify whether you want message pass_through or not. Restart required.
    pass_through: typing.Optional[bool] = Field(None, alias='pass_through')

    # Receive a notification that a message is sent to server. When true, you will receive a message indicating that a message has been sent. If false (default), you will not receive notification.
    sent_status: typing.Optional[bool] = Field(None, alias='sent_status')

    # Multiconnect: Maximum amount of seconds a Master node waits for a Coreapp node to respond to a heartbeat before considering it unhealthy and starting the failover process.
    unhealthy_interval: typing.Optional[int] = Field(None, alias='unhealthy_interval')

    webhooks: typing.Optional[Webhooks] = Field(None, alias='webhooks')
    class Config:
        arbitrary_types_allowed = True
