# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.check_contact_request_body_contacts import CheckContactRequestBodyContacts

class CheckContactRequestBody(BaseModel):
    contacts: CheckContactRequestBodyContacts = Field(alias='contacts')

    # Blocking determines whether the request should wait for the processing to complete (synchronous) or not (asynchronous).
    blocking: typing.Optional[Literal["no_wait", "wait"]] = Field(None, alias='blocking')
    class Config:
        arbitrary_types_allowed = True
