# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CheckContact(BaseModel):
    # The value you sent in the contacts field of the JSON request.
    input: typing.Optional[str] = Field(None, alias='input')

    # Status of the user.
    status: typing.Optional[Literal["processing", "valid", "invalid"]] = Field(None, alias='status')

    # WhatsApp user identifier that can be used in other API calls. Only returned if the status is valid.
    wa_id: typing.Optional[str] = Field(None, alias='wa_id')
    class Config:
        arbitrary_types_allowed = True
