# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.address import Address
from whats_app_business_python_sdk.pydantic.contact_ims import ContactIms
from whats_app_business_python_sdk.pydantic.email import Email
from whats_app_business_python_sdk.pydantic.name import Name
from whats_app_business_python_sdk.pydantic.org import Org
from whats_app_business_python_sdk.pydantic.phone import Phone
from whats_app_business_python_sdk.pydantic.url import Url

class Contact(BaseModel):
    # Full contact address(es)
    addresses: typing.Optional[typing.List[Address]] = Field(None, alias='addresses')

    # YYYY-MM-DD formatted string
    birthday: typing.Optional[str] = Field(None, alias='birthday')

    # Contact email address(es)
    emails: typing.Optional[typing.List[Email]] = Field(None, alias='emails')

    ims: typing.Optional[ContactIms] = Field(None, alias='ims')

    name: typing.Optional[Name] = Field(None, alias='name')

    org: typing.Optional[Org] = Field(None, alias='org')

    # Contact phone number(s)
    phones: typing.Optional[typing.List[Phone]] = Field(None, alias='phones')

    # Contact URL(s)
    urls: typing.Optional[typing.List[Url]] = Field(None, alias='urls')
    class Config:
        arbitrary_types_allowed = True
