# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DateTimeComponent(BaseModel):
    # The day of month
    day_of_month: typing.Optional[int] = Field(None, alias='day_of_month')

    # Both strings and numbers are accepted. If different from the value derived from the date (if specified), use the derived value.
    day_of_week: typing.Optional[Literal[1, 2, 3, 4, 5, 6, 7]] = Field(None, alias='day_of_week')

    # The hour
    hour: typing.Optional[int] = Field(None, alias='hour')

    # The minute
    minute: typing.Optional[int] = Field(None, alias='minute')

    # The month
    month: typing.Optional[int] = Field(None, alias='month')

    # The year
    year: typing.Optional[int] = Field(None, alias='year')
    class Config:
        arbitrary_types_allowed = True
