# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class GatewayNodeStatus(BaseModel):
    gateway_status: typing.Optional[str] = Field(None, alias='gateway_status')

    role: typing.Optional[Literal["primary_master", "secondary_master", "coreapp"]] = Field(None, alias='role')
    class Config:
        arbitrary_types_allowed = True
