# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Language(BaseModel):
    # The code of the language or locale to use — Accepts both language and language_locale formats (e.g., en and en_US).
    code: str = Field(alias='code')

    # The language policy the message should follow
    policy: Literal["fallback", "deterministic"] = Field(alias='policy')
    class Config:
        arbitrary_types_allowed = True
