# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Location(BaseModel):
    # Address of the location. Only displayed if name is present.
    address: str = Field(alias='address')

    # Latitude of the location
    latitude: str = Field(alias='latitude')

    # Longitude of the location
    longitude: str = Field(alias='longitude')

    # Name of the location
    name: str = Field(alias='name')
    class Config:
        arbitrary_types_allowed = True
