# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.currency import Currency
from whats_app_business_python_sdk.pydantic.date_time_object import DateTimeObject

class LocalizableParam(BaseModel):
    # Default text if localization fails
    default: str = Field(alias='default')

    currency: typing.Optional[Currency] = Field(None, alias='currency')

    date_time: typing.Optional[DateTimeObject] = Field(None, alias='date_time')
    class Config:
        arbitrary_types_allowed = True
