# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.message_context_mentions import MessageContextMentions

class MessageContext(BaseModel):
    # Sender Whatsapp id of context-message
    from_: typing.Optional[str] = Field(None, alias='from')

    # GroupId of context message
    group_id: typing.Optional[str] = Field(None, alias='group_id')

    # message id
    id: typing.Optional[str] = Field(None, alias='id')

    mentions: typing.Optional[MessageContextMentions] = Field(None, alias='mentions')
    class Config:
        arbitrary_types_allowed = True
