# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Phone(BaseModel):
    phone: typing.Optional[str] = Field(None, alias='phone')

    # Standard Values: CELL, MAIN, IPHONE, HOME, WORK
    type: typing.Optional[str] = Field(None, alias='type')

    # WhatsApp ID
    wa_id: typing.Optional[str] = Field(None, alias='wa_id')
    class Config:
        arbitrary_types_allowed = True
