# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class RequestCodeRequestBody(BaseModel):
    # Numerical country code for the phone number you are registering
    cc: str = Field(alias='cc')

    # Base64-encoded Verified Name certificate
    cert: str = Field(alias='cert')

    # Method of receiving your registration code
    method: Literal["sms", "voice"] = Field(alias='method')

    # Phone number you are registering, without the country code or plus symbol (+)
    phone_number: str = Field(alias='phone_number')

    # Existing 6-digit PIN — This is only required when two-factor verification is enabled on this account.
    pin: typing.Optional[str] = Field(None, alias='pin')
    class Config:
        arbitrary_types_allowed = True
