# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.error import Error
from whats_app_business_python_sdk.pydantic.meta import Meta

class Response(BaseModel):
    # Only returned with a failed request. Contains an array of error objects that are present when there is an error. 
    errors: typing.Optional[typing.List[Error]] = Field(None, alias='errors')

    meta: typing.Optional[Meta] = Field(None, alias='meta')
    class Config:
        arbitrary_types_allowed = True
