# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.audio import Audio
from whats_app_business_python_sdk.pydantic.contact import Contact
from whats_app_business_python_sdk.pydantic.document import Document
from whats_app_business_python_sdk.pydantic.hsm import Hsm
from whats_app_business_python_sdk.pydantic.image import Image
from whats_app_business_python_sdk.pydantic.location import Location
from whats_app_business_python_sdk.pydantic.message_type import MessageType
from whats_app_business_python_sdk.pydantic.text import Text
from whats_app_business_python_sdk.pydantic.video import Video

class SendMessageRequestBody(BaseModel):
    # When recipient_type is individual, this field is the WhatsApp ID (phone number) returned from contacts endpoint. When recipient_type is group, this field is the WhatsApp group ID.
    to: str = Field(alias='to')

    audio: typing.Optional[Audio] = Field(None, alias='audio')

    contacts: typing.Optional[typing.List[Contact]] = Field(None, alias='contacts')

    document: typing.Optional[Document] = Field(None, alias='document')

    hsm: typing.Optional[Hsm] = Field(None, alias='hsm')

    image: typing.Optional[Image] = Field(None, alias='image')

    location: typing.Optional[Location] = Field(None, alias='location')

    # Specifying preview_url in the request is optional when not including a URL in your message. To include a URL preview, set preview_url to true in the message body and make sure the URL begins with http:// or https://. For more information, see the Sending URLs in Text Messages section.
    preview_url: typing.Optional[bool] = Field(None, alias='preview_url')

    # Determines whether the recipient is an individual or a group Specifying recipient_type in the request is optional when the value is individual. However, recipient_type is required when using group. If sending a text message to a group, see the Sending Group Messages documentation.
    recipient_type: typing.Optional[Literal["individual", "group"]] = Field(None, alias='recipient_type')

    text: typing.Optional[Text] = Field(None, alias='text')

    ttl: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='ttl')

    type: typing.Optional[MessageType] = Field(None, alias='type')

    video: typing.Optional[Video] = Field(None, alias='video')
    class Config:
        arbitrary_types_allowed = True
