# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SetShardsRequestBody(BaseModel):
    cc: str = Field(alias='cc')

    phone_number: str = Field(alias='phone_number')

    pin: str = Field(alias='pin')

    shards: Literal[1, 2, 4, 8, 16, 32] = Field(alias='shards')
    class Config:
        arbitrary_types_allowed = True
