# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class WebhookLocation(BaseModel):
    # Address of the location
    address: typing.Optional[str] = Field(None, alias='address')

    # Latitude of location being sent
    latitude: typing.Optional[typing.Union[int, float]] = Field(None, alias='latitude')

    # Longitude of location being sent
    longitude: typing.Optional[typing.Union[int, float]] = Field(None, alias='longitude')

    # Name of the location
    name: typing.Optional[str] = Field(None, alias='name')

    # URL for the website where the user downloaded the location information
    url: typing.Optional[str] = Field(None, alias='url')
    class Config:
        arbitrary_types_allowed = True
