# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.error import Error
from whats_app_business_python_sdk.pydantic.webhook_contact import WebhookContact
from whats_app_business_python_sdk.pydantic.webhook_message import WebhookMessage
from whats_app_business_python_sdk.pydantic.webhook_status import WebhookStatus

class WebhookEvent(BaseModel):
    contacts: typing.Optional[typing.List[WebhookContact]] = Field(None, alias='contacts')

    errors: typing.Optional[typing.List[Error]] = Field(None, alias='errors')

    messages: typing.Optional[typing.List[WebhookMessage]] = Field(None, alias='messages')

    statuses: typing.Optional[typing.List[WebhookStatus]] = Field(None, alias='statuses')
    class Config:
        arbitrary_types_allowed = True
