# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from whats_app_business_python_sdk.pydantic.error import Error

class WebhookStatus(BaseModel):
    errors: typing.Optional[typing.List[Error]] = Field(None, alias='errors')

    # Message ID
    id: typing.Optional[str] = Field(None, alias='id')

    # WhatsApp ID of recipient
    recipient_id: typing.Optional[str] = Field(None, alias='recipient_id')

    # Status of message
    status: typing.Optional[Literal["sent", "delivered", "read", "failed", "deleted"]] = Field(None, alias='status')

    # Timestamp of the status message
    timestamp: typing.Optional[str] = Field(None, alias='timestamp')
    class Config:
        arbitrary_types_allowed = True
