# coding: utf-8

"""
    WhatsApp Business API

    See https://developers.facebook.com/docs/whatsapp

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Webhooks(BaseModel):
    # Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.
    max_concurrent_requests: typing.Optional[Literal[6, 12, 18, 24]] = Field(None, alias='max_concurrent_requests')

    # Inbound and outbound notifications are routed to this URL. A HTTPS-based endpoint is required; HTTP will not work.
    url: typing.Optional[str] = Field(None, alias='url')
    class Config:
        arbitrary_types_allowed = True
